### ISSUE TITLE
`face_colors` Property missing?

### ISSUE THREAD

**Issue by ricaun** [paireks/dotbim#18]
I was trying to create a viewer using three.js and manage to make work fine but I tested some files and found this `face_colors` that does not exist in the schema.

Looks like this `face_colors` is the color of each face when the mesh needs to have different colors.

https://github.com/kovacsv/dotbim-archicad/blob/d50b54a33c586090b3fee947cf67c8268c201244/Sources/AddOn/DotbimExporter.cpp#L188

**Comment by paireks** [comment]
Yes, you're right, there is no face_colors right now, as it is an extension of a schema described here: https://github.com/paireks/dotbim-extensions-multicolor, while the library keeps core schema (same is with Typescript and Python library).

Generally as simple as it looks at first glance - it's actually quite complex (and subjective) topic on multiple levels. I can discuss it here or in DM if you want cause it will take a while :)

Right now as far as I know currently face_colors extension is supported by Archicad plugin and Online3dViewer.

**Comment by ricaun** [comment]
I just found it a little odd that the face_colors are in the Element and not inside the Mesh with the indices and coordinates.

Could be neat to have work in both places actually. DM probably gonna be better 😁

**Comment by ricaun** [comment]
Kinda work!

![image](https://user-images.githubusercontent.com/12437519/211903913-d66bdacb-e497-42e7-b515-13b1234d0c79.png)

**Comment by paireks** [comment]
Wow, it looks amazing!

Let me know if you will decide to release it somewhere!

**Comment by ricaun** [comment]
Here is a base implementation: https://github.com/ricaun/dotbim.three.js

I propose to create propriety in the `mesh` called `colors` with something like this `[ir,ig,ib,ia,jr,jg,jb,ja...]` with one color for each face or one default color for all the faces in the mesh.

And the `color` in the element became optional and should overwrite the color in the mesh in a viewer. I believe makes more sense to remove the `face_colors` in the element and move to the mesh.

**Comment by paireks** [comment]
I believe that such change of an extension then should be proposed here first: https://github.com/paireks/dotbim-extensions-multicolor and then question for @kovacsv if Viktor likes it and agrees with it, and if he wants to change it in archicad plugin and Online 3d Viewer.

Then after that there is an open question how to handle extensions inside libraries like this one in C# but also in Python and Typescript libraries. Right now they all only holds data for core-schema, so it's quite straight-forward and doesn't require updates. I guess the default option would be to add there the properites for every extension there, but that could make it much more difficult and dirty if there will be more than 1 extensions as it is right now. E.g. I was considering adding extension where you do not color it by faces, but by vertices. Someone else could add extension for textures. And then we will find ourselves with 4 different methods of coloring objects in one schema that claimed itself as minimalist :) So open question is: should we (and how) support all extensions in libraries in a smart way without complicating it.

**Comment by kovacsv** [comment]
Defining `face_colors` on mesh level provides the ability to reuse meshes with different colors. For example you are able to place the same chair 10 times, all with different colors. On the other hand it would make sense to provide default `face_colors` on mesh level so it's used when there are no `face_colors` on element level. It would keep the flexibility, and the format would still remain backward compatible.

**Comment by ricaun** [comment]
I don't think the extension in the main dotbim schema is a good idea, it all depends on the purpose of the dotbim. 

This multicolor definitely is missing in the main schema, with `colors` probably, should be possible to make the `colors` work with faces or vertex depending on how many colors you provide in the array.

Now I don't know if makes sense to add `colors` or `face_colors` in the element level, makes it more flexible but I make the element really connected with the number of faces in the `mesh_id`.

**Comment by paireks** [comment]
If it should be in the main is actually really subjective. I had some long discussions in the past that e.g. supporting breps in the main schema is missing. Or maybe textures should be in the main schema? Also in the past the discussions was that in main schema I should add standardization of naming things (like in IFC providing how we should call beam, wall, and so on) :)

The goal of dotbim was to be as minimalist as it could be, yet still make it possible to transfer meshes with attached properties, which is in my opinion essence of BIM (some disagree on that ;)). The most minimalist way of handling colors is one color per element. 

For most of the cases it is actually enough: e.g. all Tekla Structures models I've seen had such limitation, yet it still works and I've never seen anyone missing this feature. I believe MEP models similiarly deal with it. Cases where it's actually needed are the detailed models modelled by architects, where they actually want to color doors, windows, furnitures. Does it mean that with one color per element we cannot transfer it? Not really, because we still can disassemble by  colors and send it like this. You can see models like this here: https://3dviewer.net/#model=https://raw.githubusercontent.com/paireks/dotbim/master/test/ExampleFiles/TestFilesFromBlender/Chair%2001.bim

The disanvantage of such approach is that rather than having 1 element you will have 2 or more then. That's why Viktor came up with the idea, that OK, if you want to have multiple colors on object and still have it as one element - place the colors there. Thing is later I've tried to apply it in various other places, and it's not so easy to apply everywhere. In Grasshopper there is not really an option to color one mesh with various different face colors. You have to disasseble it to multiple different elements, and color it separately. So still we are back in the same spot, that we have to disassemble it, but right now not on an exporter side, but importer side, and the result will be the same: multiple elements representing one :) 

So because feature is really specific and because there can always be someone wanted to add something, color it differently (e.g. if someone wanted to transfer the colorful results of analysis by this, then vertex colors will be needed), the decision was that to put such features as an extensions rather than make the core grow same as it looks like for other schemas, that are constantly being expanded and developed, so they become more and more complex during the years to satisfy every workflow and everyone :)

**Comment by ricaun** [comment]
The only way to create a cube with different face color in the current schema is creating 6 meshes and 6 element. And if I want 10 cubes instead I gonna need 60 elements, and if I need to change the color of one face I gonna need to change in each element that has that face.
The only reason that I have been start using dotbim is that is a Json standard for mesh/element and work in multiple platform, that viewer that can convert to a .bim file is really neat.
But technically the only want to get the face_colors in the current package is no using the package...
Maybe the schema should have a parameter like the info, a special place to add extension, a dictionary<string, object>. I don't know if is a good ideia, but adding colors in the mesh gonna maks mush easyer to work with the default package.
Probably gonna create my meshcolor extension...

**Comment by paireks** [comment]
Hmm, the idea of a dictionary<string, object> for extensions is pretty interesting, I will think about, maybe that will ressolve this :)
If there would be something like extension properties (similiar to extension methods), then that would work :D
I will think about it and let you know, if you will come up with something else as well, please let me know, cause sure it should be solved :)

**Comment by ricaun** [comment]
Extension properties does not exist 🥲
Would be possible to add the extension in the Info like a Json text, extension_face_colors... 

A place for the extension using dictionary<string, object> probably is better. So each extension could have an 'oficial' name with a custom schema. And could be ignored pretty easy.

Now I need to convince you to add the colors propriety in the mesh, with no color, one color, one color for each face and one color for each corner in the face. 😁

**Comment by paireks** [comment]
Ok, so after thinking for a while - I will check how <string,  object> idea would work in a different places, and will be back with some answers, it will probably take a while. I plan also to reconsider adding face_colors to main schema, so will let you know as well.

For now I really recommend using this library as a submodule if you want to get face_colors and still use this library (rather than doing it by Nuget). Because this way you can plug this repo as a submodule, extend it the way you want it locally and move on. It's not perfect solution, but it should work for now.

Let's be in touch :)

**Comment by ricaun** [comment]
Yep, I gonna create my own version and make some tests, gonna be easy to change the import and export locally in the Online3DViewer and make some tests.

https://github.com/kovacsv/Online3DViewer/blob/master/source/engine/import/importerbim.js

**Comment by kovacsv** [comment]
Ping me when you agree on the file format modification. I'm happy to implement it in Online3DViewer, and even more happier to see a pull request. 🙂

**Comment by ricaun** [comment]
@kovacsv I was trying some implementation in the Online3DViewer and was not able to make work to add color in a vertex mode, like each corner in a triangle with one color. Looks like only supports RGB and not RGBA. This means gonna be a pain to support vertex color, I made work to support one color for the whole mesh or by triangle faces.

Another thing I discovered by testing is all the proprieties in the scheme are obligatory and if someone is missing makes the 3DViewer break. Now I kinda understand the reason the face_colors is in the element level and the color has a default value.

The [dotbim.three.js](https://github.com/ricaun/dotbim.three.js) works now with both implementation `face_colors` in element and `colors` in mesh.

**Comment by kovacsv** [comment]
Vertex colors are completely different. It's supported by Online3DViewer, but not by most of the BIM applications. Anyway, if you agree on the format, I'll implement it in the viewer.

**Comment by paireks** [comment]
If vertex colors are not supported by most of BIM apps then screw that :)

**Comment by ricaun** [comment]
Just faces then! 😁 

The file is not optimized, I have duplicated meshes in different rotations, and have the `colors` in the mesh and the `face_colors` to make work in the 3DViewer, the file is enormous I'm glad that .zip format works.

https://3dviewer.net/#model=https://github.com/ricaun/dotbim.three.js/blob/develop/models/rac_advanced_sample_project.zip

**Comment by paireks** [comment]
@ricaun wow, it looks great!

Ok, I think I finally grown up to the idea of merging face_colors into main schema and call it "1.1.0". Especially knowing that it's last puzzle needed most likely :) Question is if we should do it as it is defined in the extension (face_colors inside elements, so there will be nothing to change by Viktor) or we place it inside mesh instead. I don't want to make it possible to place it in both places, it makes sense, but I prefer having one way possible :)

**Comment by ricaun** [comment]
I like the idea to add in the mesh level, so if someone have 10 at the same windows, I only need one mesh and 10 element each one with a different position and rotation, and the information about the colors is apply in the mesh.

The only problem I see is the color in the Element is kinda opcional, and the colors in the mesh optional too.

I changed the struct color to class so by default is null, the 3dviewer is not prepared for null values but could be great to make optional as well.

Maybe all the struct could be class and when serializing just make ignore what is null, the output file would be smaller but all the reader/viewer will need to handle that.

**Comment by paireks** [comment]
Placing face_colors inside mesh (instead of placing it inside element) seems ok, it won't allow workflow that Viktor described (coloring one chair in a various ways without duplicating meshes), but I think it's still acceptable.

You're right with optional tags, I have with these problems as well. Generally:
1. I think I will keep color inside element as obligatory <- this will make sure, that it's backward compatible, and all the old files and old connectors will be working, and colored just by the color inside elements, just as it was.
2. But regarding face_colors if they should be optional or obligatory - I don't know right now. Making it optional will be okay only if I will make sure that optional tags can be handled anywhere properly (not only for C# and viewers, but also Python and TS libraries and all other connectors).

Right now (in 1.0.0) all tags are obligatory (even if e.g. Vector is 0,0,0) and that simplifies a lot of things, cause without it there would be multiple checks required in every connector and viewer. So I think making face_colors obligatory would also simplify the whole process.

The only downside is having 2 different coloring methods at the same time.
- for viewers I think coloring it with face_colors, but if not applied -> with element's color (just as Viktor done it :)) seems correct
- for Grasshopper I think I can do some sort of a button that can switch between these both methods depending what user will pick
- for Blender I have to ask @Gorgious56 ;) I remember we talked about it, but I can't remember the conclusion different than we should be able to make it :)
and also I will have to find out in other projects as well.

+ We will have to update all the documentation drawings, but hopefuly maybe @rojus will help me with that ;)

I pushed a new branch here for that: https://github.com/paireks/dotbim/tree/schema_development/1_1_0 and will do same thing for e.g. Python library to check on these branches how well this works.

**Comment by ricaun** [comment]
The only problem with having color in the element and face_colors or colors in the mesh will be what the viewer could use. 
How the viewer/application gonna know what color to use? 

Imagine I have 2 elements pointing to one mesh with face_colors and that makes the color in the element level kinda useless, or maybe I want to show one mesh with red and blue, but the mesh has colors. 

That's why I think color/colors should be optional, but I really don't know, or maybe the color 0,0,0,0 should be used to ignore. In C# the color is defined as a struct and the default is 0,0,0,0 so maybe the viewer could ignore the color and use the colors in the mesh level.

**Comment by kovacsv** [comment]
It can just work based the _use the most specific_ rule (like in inheritance in programming).

So something like this:
1. If there are `face_colors` defined on `element` level, use them. Otherwise:
2. If there is a `color` defined on `element` level, use that. Otherwise:
3. If there are `face_colors` defined on `mesh` level, use them. Otherwise:
4. Use the `color` on mesh level which is a mandatory member.

It would provide full flexibility and keeps it compatible with older versions. On the other hand it makes the import implementation a bit more complex. If we would like to optimize for simplicity, I would put every color information on mesh level (even though it's a breaking change, and doesn't allow to reuse the same geometry with different colors).

**Comment by paireks** [comment]
One thing that is really important to me is backward compatibility, so naturally breaking changes are something I would avoid.

Side note regarding color in elements: I already use it a lot, I have some 3d symbols that I store once and then color it differently, place different metadata for each one, and it works great.

Maybe let's just make it as it is already in the Online 3d Viewer then, and treat is with these two points only:
1. If there are `face_colors` defined on `element` level, use them. Otherwise:
2. Use `color` defined on `element` level.

**Comment by ricaun** [comment]
This extension `face_colors` is a branch of the default schema and I agree with backward compatibility, but.

Gonna be a nightmare to provide backward compatible for all the extension, I suppose only exist this one but imagine 10 extension how manage that... The extension propriety kinda makes sense.

In my opinion only add a `colors` in the `mesh` level and should work something like:
- if there are `color` define on the `element` level, use them. otherwise:
- Use `colors` defined on the `mesh` level. 

The `color` in the Element level gonna work like a overwrite.

This way is not gonna be backward compatible with this extension and gonna work fine with the main schema.

**Comment by paireks** [comment]
We have added face_colors to elements, updated documentation and updated version to 1.1.0 here: https://github.com/paireks/dotbim/tree/schema_development/1_1_0

Will merge with master soon.

**Comment by ricaun** [comment]
> We have added face_colors to elements, updated documentation and updated version to 1.1.0 here: https://github.com/paireks/dotbim/tree/schema_development/1_1_0
> 
> Will merge with master soon.

I am kinda disappointed that you decide to add the `face_colors` in the element instead of the mesh.

**Comment by paireks** [comment]
I see, at least the functionality that was missing is there :) The fact that you convinced me to update something in schema is already huge thing, as this project is more about reduction than addition, so I try to keep it as minimalist as I can. Regularly someone asks if I can add this, and this and that, and regularly I have to say no, because this project won't be original anymore if I will try to satisfy everybody, and naturally it will become another complex standard like other that already exist. I'm sorry it's not 100% the way you wanted it to be, I hope you will still find it useful :)
