### ISSUE TITLE
Question: possible to infer aggregation hierarchy from dotbim file?

### ISSUE THREAD

**Issue by xeolabs** [paireks/dotbim#37]
Hi @paireks, I'm working on a dotbim importer for xeokit SDK, which likes to organize elements in an aggregation hierarchy for our explorer tree etc. We have three modes: "Containment", "Storeys" and "Types". 

Apologies if I'm missing something, a question: the dotbim schema seems to have no explicit relationships (eg. containment/aggregation) between the elements, unless I'm missing something. Is there a way to get or infer that hierarchy (IfcSite, IfcBuildingStorey etc), or is dotbim more like a flattened container of graphical "leaf" elements?

We should be able to support "Types" in our tree at least though.

Thanks!

**Comment by paireks** [comment]
Hello @xeolabs :)

Yes, there is no explicit relationships between the elements, it's a flatened container of elements.

What I personally do to describe relationships is:
1. putting e.g. "Parent Guid" as an additional key in the "info" dictionary with a proper guid of an element (in other words: using "info" dictionary to tell more about hierarchy)
2. putting a reference link if models are separated: https://github.com/paireks/dotbim/blob/master/LinkingData.md#linking-models-multilevel-bim

But both approaches are just tips, because there are no written rules how to handle it.

**Comment by xeolabs** [comment]
Cool that makes sense - we can just have xeokit look for a "Parent Guid" in the info, and also make the key for that a configurable thing in xeokit. 
Thanks @paireks !
